[paws] Document apis used in all collectors
alertlogic/paws-collector pull request #143
Opened 2020-08-26 12:55 UTC by surajkadam

2020-08-26 16:07 UTC, JDragovichAlertLogic requested changes
Looks good so far suraj. Thanks

2020-08-26 16:07 UTC, JDragovichAlertLogic commented on collectors/carbonblack/package.json
> +  "version": "1.0.6",
we doint need to bump the verison when we just do readme updates

2020-08-26 16:07 UTC, JDragovichAlertLogic commented on collectors/sentinelone/package.json
> +  "version": "1.0.5",
see previous comment

2020-08-26 16:07 UTC, JDragovichAlertLogic commented on collectors/sophos/package.json
> +  "version": "1.0.3",
See previous comment

2020-08-26 16:07 UTC, JDragovichAlertLogic commented on collectors/sophossiem/package.json
> +  "version": "1.0.2",
see previous comment

2020-08-26 16:07 UTC, JDragovichAlertLogic commented on collectors/sophossiem/README.md
> +1. How to send alert and event data to your SIEM [Link](https://support.sophos.com/support/s/article/KB-000036372?language=en_US)
I would include instructions on how to access the swagger definition.

2020-09-07 15:22 UTC, JDragovichAlertLogic requested changes
Thanks Suraj. a few comments

2020-09-08 11:07 UTC, surajkadam commented on collectors/o365/README.md
>  1. Locate the `Office 365 Management APIs`, and then click `Select`.
Yes, Sure Joe, But I need credentials for O365. I'll add screenshots as well if I get credentials.

2020-09-10 08:51 UTC, JDragovichAlertLogic approved these changes
Looks good. thanks for doing this Suraj

2020-09-10 08:51 UTC, merged